from pathlib import Path

path = Path('src/App.tsx')
text = path.read_text(encoding='utf-8')
text = text.replace('\r\n', '\n')
replacements = [
    (
        "  const addDefect = async (e: React.FormEvent<HTMLFormElement>) => {\n    e.preventDefault();\n    const formData = new FormData(e.currentTarget);\n    const orderId = Number(formData.get('orderId')) || null;\n    const type = formData.get('type') as 'entry' | 'exit';\n    const quantity = Number(formData.get('quantity'));\n    const reason = formData.get('reason') as string;\n    const date = formData.get('date') as string;\n\n    if (!quantity || quantity <= 0) {\n      setError('A quantidade deve ser maior que zero.');\n      return;\n    }\n\n    try {\n      const res = await fetch('/api/defects', {\n        method: 'POST',\n        headers: { 'Content-Type': 'application/json' },\n        body: JSON.stringify({ orderId, type, quantity, reason, date })\n      });\n      const data = await res.json();\n      if (data.success) {\n        setIsDefectModalOpen(false);\n        fetchData();\n        setSuccess('Defeito registrado com sucesso!');\n      } else {\n        setError(data.error || data.message || 'Erro ao lançar defeito');\n      }\n    } catch (err) {\n      setError('Erro ao conectar ao servidor. Verifique se o banco de dados está rodando e se o Supabase está configurado corretamente.');\n    }\n  };\n",
        "  const addDefect = async (e: React.FormEvent<HTMLFormElement>) => {\n    e.preventDefault();\n    const formData = new FormData(e.currentTarget);\n    const orderId = Number(formData.get('orderId')) || null;\n    const type = formData.get('type') as 'entry' | 'exit';\n    const quantity = Number(formData.get('quantity'));\n    const reason = formData.get('reason') as string;\n    const date = formData.get('date') as string;\n\n    if (!quantity || quantity <= 0) {\n      setError('A quantidade deve ser maior que zero.');\n      return;\n    }\n\n    try {\n      if (isSupabaseConfigured) {\n        await supabaseInsert<Defect>('defects', { orderId, type, quantity, reason, date });\n        setIsDefectModalOpen(false);\n        fetchData();\n        setSuccess('Defeito registrado com sucesso!');\n        return;\n      }\n\n      const res = await fetch('/api/defects', {\n        method: 'POST',\n        headers: { 'Content-Type': 'application/json' },\n        body: JSON.stringify({ orderId, type, quantity, reason, date })\n      });\n      const data = await res.json();\n      if (data.success) {\n        setIsDefectModalOpen(false);\n        fetchData();\n        setSuccess('Defeito registrado com sucesso!');\n      } else {\n        setError(data.error || data.message || 'Erro ao lançar defeito');\n      }\n    } catch (err) {\n      setError('Erro ao conectar ao servidor. Verifique se o banco de dados está rodando e se o Supabase está configurado corretamente.');\n    }\n  };\n"
    ),
    (
        "  const deleteDefect = async (id: number) => {\n    triggerConfirm(\n      \"Excluir Lançamento de Defeito\",\n      \"Tem certeza que deseja excluir este lançamento? Esta ação não pode ser desfeita.\",\n      async () => {\n        try {\n          const res = await fetch(`/api/defects/${id}`, { method: 'DELETE' });\n          const data = await res.json();\n          if (data.success) {\n            fetchData();\n          }\n        } catch (err) {\n          setError('Erro ao excluir defeito');\n        }\n      }\n    );\n  };\n",
        "  const deleteDefect = async (id: number) => {\n    triggerConfirm(\n      \"Excluir Lançamento de Defeito\",\n      \"Tem certeza que deseja excluir este lançamento? Esta ação não pode ser desfeita.\",\n      async () => {\n        try {\n          if (isSupabaseConfigured) {\n            await supabaseDelete('defects', id);\n            fetchData();\n            return;\n          }\n\n          const res = await fetch(`/api/defects/${id}`, { method: 'DELETE' });\n          const data = await res.json();\n          if (data.success) {\n            fetchData();\n          }\n        } catch (err) {\n          setError('Erro ao excluir defeito');\n        }\n      }\n    );\n  };\n"
    ),
    (
        "  const saveRepair = async (e: React.FormEvent<HTMLFormElement>) => {\n    e.preventDefault();\n    const formData = new FormData(e.currentTarget);\n    const pId = Number(formData.get('productId'));\n    \n    if (!pId) {\n      setError('Selecione um produto.');\n      return;\n    }\n\n    if (repairItemsBreakdown.length === 0) {\n      setError('Adicione pelo menos uma cor e tamanho para o concerto.');\n      return;\n    }\n\n    const data = {\n      productId: pId,\n      type: formData.get('type') as 'entry' | 'exit',\n      date: formData.get('date') as string,\n      notes: formData.get('notes') as string,\n      items: repairItemsBreakdown\n    };\n\n    try {\n      const res = await fetch('/api/repairs', {\n        method: 'POST',\n        headers: { 'Content-Type': 'application/json' },\n        body: JSON.stringify(data)\n      });\n      const resData = await res.json();\n      if (resData.success) {\n        setIsRepairModalOpen(false);\n        setRepairItemsBreakdown([]);\n        fetchData();\n        setSuccess('Concerto registrado com sucesso!');\n      } else {\n        setError(resData.error || resData.message || 'Erro ao lançar concerto');\n      }\n    } catch (err) {\n      setError('Erro ao conectar ao servidor. Verifique se o banco de dados está configurado.');\n    }\n  };\n",
        "  const saveRepair = async (e: React.FormEvent<HTMLFormElement>) => {\n    e.preventDefault();\n    const formData = new FormData(e.currentTarget);\n    const pId = Number(formData.get('productId'));\n    \n    if (!pId) {\n      setError('Selecione um produto.');\n      return;\n    }\n\n    if (repairItemsBreakdown.length === 0) {\n      setError('Adicione pelo menos uma cor e tamanho para o concerto.');\n      return;\n    }\n\n    const data = {\n      productId: pId,\n      type: formData.get('type') as 'entry' | 'exit',\n      date: formData.get('date') as string,\n      notes: formData.get('notes') as string,\n      items: repairItemsBreakdown\n    };\n\n    try {\n      if (isSupabaseConfigured) {\n        await supabaseInsert<Repair>('repairs', data);\n        setIsRepairModalOpen(false);\n        setRepairItemsBreakdown([]);\n        fetchData();\n        setSuccess('Concerto registrado com sucesso!');\n        return;\n      }\n\n      const res = await fetch('/api/repairs', {\n        method: 'POST',\n        headers: { 'Content-Type': 'application/json' },\n        body: JSON.stringify(data)\n      });\n      const resData = await res.json();\n      if (resData.success) {\n        setIsRepairModalOpen(false);\n        setRepairItemsBreakdown([]);\n        fetchData();\n        setSuccess('Concerto registrado com sucesso!');\n      } else {\n        setError(resData.error || resData.message || 'Erro ao lançar concerto');\n      }\n    } catch (err) {\n      setError('Erro ao conectar ao servidor. Verifique se o banco de dados está configurado.');\n    }\n  };\n"
    ),
    (
        "  const deleteRepair = async (id: number) => {\n    triggerConfirm(\n      \"Excluir Registro de Concerto\",\n      \"Tem certeza que deseja excluir este registro? Esta ação não pode ser desfeita.\",\n      async () => {\n        try {\n          const res = await fetch(`/api/repairs/${id}`, { method: 'DELETE' });\n          const data = await res.json();\n          if (data.success) {\n            fetchData();\n            setSuccess('Concerto excluído com sucesso!');\n          } else {\n            setError(data.error || data.message || 'Erro ao excluir concerto');\n          }\n        } catch (err) {\n          setError('Erro ao excluir concerto');\n        }\n      }\n    );\n  };\n",
        "  const deleteRepair = async (id: number) => {\n    triggerConfirm(\n      \"Excluir Registro de Concerto\",\n      \"Tem certeza que deseja excluir este registro? Esta ação não pode ser desfeita.\",\n      async () => {\n        try {\n          if (isSupabaseConfigured) {\n            await supabaseDelete('repairs', id);\n            fetchData();\n            setSuccess('Concerto excluído com sucesso!');\n            return;\n          }\n\n          const res = await fetch(`/api/repairs/${id}`, { method: 'DELETE' });\n          const data = await res.json();\n          if (data.success) {\n            fetchData();\n            setSuccess('Concerto excluído com sucesso!');\n          } else {\n            setError(data.error || data.message || 'Erro ao excluir concerto');\n          }\n        } catch (err) {\n          setError('Erro ao excluir concerto');\n        }\n      }\n    );\n  };\n"
    )
]
for old, new in replacements:
    if old not in text:
        raise ValueError('Pattern not found')
    text = text.replace(old, new)
path.write_text(text.replace('\n','\r\n'), encoding='utf-8')
print('patched addDefect/deleteDefect/saveRepair/deleteRepair')
