-- Full Supabase schema for Confecção Pro
-- Generated migration: 2024-06-06

-- 1. Tabela de Funcionários
CREATE TABLE IF NOT EXISTS employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT,
  daily_rate DECIMAL(10,2) DEFAULT 0,
  cpf TEXT,
  address TEXT,
  pix_key TEXT,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_employees_active ON employees(active);

-- 2. Tabela de Diárias (Shifts)
CREATE TABLE IF NOT EXISTS shifts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id BIGINT REFERENCES employees(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  status TEXT DEFAULT 'pending',
  notes TEXT,
  is_half_day BOOLEAN DEFAULT false,
  hours_worked DECIMAL(5,2),
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_shifts_date ON shifts(date);
CREATE INDEX IF NOT EXISTS idx_shifts_employee ON shifts(employee_id);

-- 3. Tabela de Clientes
CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  address TEXT,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabela de Fornecedores
CREATE TABLE IF NOT EXISTS suppliers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  category TEXT,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tabela de Produtos
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  sku TEXT,
  category TEXT,
  technical_sheet TEXT,
  photos TEXT[],
  colors TEXT[],
  sizes TEXT[],
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Tabela de Ordens de Produção
CREATE TABLE IF NOT EXISTS production_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description TEXT NOT NULL,
  client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  total_pieces INTEGER NOT NULL DEFAULT 0,
  unit_price DECIMAL(10,2) DEFAULT 0,
  total_value DECIMAL(10,2) DEFAULT 0,
  status TEXT DEFAULT 'planning',
  priority TEXT DEFAULT 'medium',
  order_number TEXT,
  start_date DATE NOT NULL DEFAULT CURRENT_DATE,
  end_date DATE,
  items JSONB DEFAULT '[]',
  items_breakdown JSONB DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_po_status ON production_orders(status);
CREATE INDEX IF NOT EXISTS idx_po_client ON production_orders(client_id);

-- 7. Tabela de Lançamentos de Produção (Etapas)
CREATE TABLE IF NOT EXISTS production_steps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES production_orders(id) ON DELETE CASCADE,
  employee_id BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  step_type TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 0,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_steps_order ON production_steps(order_id);

-- 8. Tabela Financeira
CREATE TABLE IF NOT EXISTS financial_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  category TEXT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  paid_amount DECIMAL(10,2) DEFAULT 0,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  description TEXT,
  related_id BIGINT,
  client_name TEXT,
  status TEXT DEFAULT 'completed',
  due_date DATE,
  finished_date DATE,
  reconciled BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_finance_date ON financial_transactions(date);
CREATE INDEX IF NOT EXISTS idx_finance_type ON financial_transactions(type);

-- 9. Tabela de Defeitos
CREATE TABLE IF NOT EXISTS defects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES production_orders(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 0,
  reason TEXT,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Tabela de Concertos
CREATE TABLE IF NOT EXISTS repairs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 0,
  color TEXT,
  size TEXT,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. Tabela de Configurações da Empresa
CREATE TABLE IF NOT EXISTS company_settings (
  id BIGINT PRIMARY KEY DEFAULT 1,
  name TEXT NOT NULL DEFAULT 'Confecção Pro',
  document_type TEXT,
  document_number TEXT,
  state_registration TEXT,
  rg TEXT,
  address TEXT,
  city TEXT,
  logo_url TEXT,
  pdf_background_color TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT single_row CHECK (id = 1)
);

-- 12. Tabela de Usuários
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  role TEXT DEFAULT 'user',
  biometric_credential JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- INSERTS INICIAIS
INSERT INTO company_settings (id, name)
VALUES (1, 'Confecção Pro')
ON CONFLICT (id) DO NOTHING;

INSERT INTO users (username, password, role)
VALUES ('admin', 'admin', 'admin')
ON CONFLICT (username) DO NOTHING;

INSERT INTO users (username, password, role)
VALUES ('fasbbrazil@gmail.com', 'admin', 'admin')
ON CONFLICT (username) DO NOTHING;

INSERT INTO users (username, password, role)
VALUES ('francielebrazil@gmail.com', 'admin', 'admin')
ON CONFLICT (username) DO NOTHING;

-- Em colunas IDENTITY, o PostgreSQL gerencia a sequência automaticamente;
-- não é necessário ajustar sequências manualmente aqui.
