-- Create employees table
CREATE TABLE IF NOT EXISTS employees (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  daily_rate DECIMAL NOT NULL DEFAULT 0,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create shifts table
CREATE TABLE IF NOT EXISTS shifts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  amount DECIMAL NOT NULL DEFAULT 0,
  status TEXT DEFAULT 'pending',
  notes TEXT,
  is_half_day BOOLEAN DEFAULT FALSE,
  hours_worked DECIMAL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE shifts ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Enable all access for all users" ON employees FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for all users" ON shifts FOR ALL USING (true) WITH CHECK (true);
